# Generated by Django 2.2.12 on 2020-06-13 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='new_project',
            options={'ordering': ['-created'], 'verbose_name': 'Mi Proyecto', 'verbose_name_plural': 'Mis Proyectos'},
        ),
        migrations.AddField(
            model_name='new_project',
            name='more_info',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='new_project',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='F. Creación'),
        ),
        migrations.AlterField(
            model_name='new_project',
            name='description',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='new_project',
            name='image',
            field=models.ImageField(upload_to='projects', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='new_project',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='F. Modificación'),
        ),
        migrations.AlterField(
            model_name='new_project',
            name='title',
            field=models.CharField(max_length=80, verbose_name='Nombre del Proyecto'),
        ),
    ]
