# Generated by Django 2.2.12 on 2020-06-13 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20200613_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_project',
            name='more_info',
            field=models.URLField(blank=True, null=True, verbose_name='Sitio Web'),
        ),
    ]
